image: atlassian/default-image:3

pipelines:

  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            - docker build --build-arg=NODE_ENV=production --build-arg=GIT_COMMIT=$BITBUCKET_COMMIT -t $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT -f Dockerfile .
            - docker tag $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:prod
            - docker push $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:prod
            - docker push $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT
            - git remote add sync git@github.com:realiotech/$BITBUCKET_REPO_SLUG.git
            - git checkout -b main
            - git push sync main
          services:
            - docker
          caches:
            - docker
    staging:
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            - docker build --build-arg=GIT_COMMIT=$BITBUCKET_COMMIT -build-arg=NODE_ENV=staging -t $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT -f Dockerfile .
            - docker tag $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:latest
            - docker push $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:latest
            - docker push $DOCKER_REGISTRY/$BITBUCKET_REPO_SLUG:$BITBUCKET_COMMIT
          services:
            - docker
          caches:
            - docker

definitions:
  services:
    docker:
      memory: 2048
