image: atlassian/default-image:3

pipelines:

  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            - docker build --build-arg=NODE_ENV=production -t $DOCKER_REGISTRY/realio-network-docs:$BITBUCKET_COMMIT .
            - docker tag $DOCKER_REGISTRY/realio-network-docs:$BITBUCKET_COMMIT $DOCKER_REGISTRY/realio-network-docs:prod
            - docker push $DOCKER_REGISTRY/realio-network-docs:prod
            - docker push $DOCKER_REGISTRY/realio-network-docs:$BITBUCKET_COMMIT
          services:
            - docker
          caches:
            - docker
    staging:
      - step:
          name: Deploy to Staging
          deployment: staging
          script:
            - docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
            - docker build --build-arg=NODE_ENV=stage -t $DOCKER_REGISTRY/realio-network-docs:$BITBUCKET_COMMIT .
            - docker tag $DOCKER_REGISTRY/realio-network-docs:$BITBUCKET_COMMIT $DOCKER_REGISTRY/realio-network-docs:latest
            - docker push $DOCKER_REGISTRY/realio-network-docs:latest
            - docker push $DOCKER_REGISTRY/realio-network-docs:$BITBUCKET_COMMIT
          services:
            - docker
          caches:
            - docker

definitions:
  services:
    docker:
      memory: 2048
